#MEU PRIMEIRO BANQUINHO
CREATE SCHEMA EC1_CC1M;

#USANDO MEU BANQUINHO
USE EC1_CC1M;

#CRIANDO A TABELINHA FORNECEDORES
CREATE TABLE IF NOT EXISTS FORNECEDORES(
#NOME DO ATRIBUTO - TIPO - RESTRIÇÃO DE INTEGRIDADE
FORNEC_COD INT PRIMARY KEY,
FORNEC_NOME VARCHAR(45) NOT NULL,
FORNEC_RUA VARCHAR(45) NOT NULL,
FORNEC_NUMRUA INT,
FORNEC_BAIRRO VARCHAR(45) NOT NULL,
FORNEC_CIDADE VARCHAR(45) NOT NULL,
FORNEC_ESTADO VARCHAR(45) NOT NULL,
FORNEC_PAIS VARCHAR(30) NOT NULL,
FORNEC_CODPOSTAL VARCHAR(10)NOT NULL,
FORNEC_TELEFONE VARCHAR(15) NOT NULL,
FORNEC_CONTATO TEXT NOT NULL);

#CRIANDO A TABELINHA PRODUTOS
CREATE TABLE IF NOT EXISTS PRODUTOS(
PROD_COD INT PRIMARY KEY,
PROD_NOME VARCHAR(50) NOT NULL,
PROD_DESCRICAO TEXT NOT NULL,
PROD_ESPECTEC TEXT NOT NULL,
PROD_QUANT DECIMAL(10,3) NOT NULL,
PROD_PRECOUNIT DECIMAL (10,2) NOT NULL,
PROD_UNIDMEDIDA VARCHAR(10) NOT NULL,
PROD_ESTOQUEMINIMO DECIMAL(10,3) NOT NULL);

#CRIANDO A TABELINHA FILIAIS
CREATE TABLE IF NOT EXISTS FILIAIS(
FILIAIS_COD INT PRIMARY KEY,
FILIAIS_NOME VARCHAR(30) NOT NULL,
FILIAIS_RUA VARCHAR(100) NOT NULL,
FILIAIS_NUMRUA INT,
FILIAIS_BAIRRO VARCHAR(50) NOT NULL,
FILIAIS_CIDADE VARCHAR(50) NOT NULL,
FILIAIS_ESTADO VARCHAR(50) NOT NULL,
FILIAIS_PAIS_ VARCHAR(50) NOT NULL,
FILIAIS_CODPOSTAL VARCHAR(10) NOT NULL,
FILIAIS_CAPACIDADE TEXT NOT NULL);

#FASE 4: CRIAR AS TABELAS COM DEPENDÊNCIA DE CHAVE ESTRANGEIRA
#CRIANDO A TABELA PEDIDOS
CREATE TABLE IF NOT EXISTS PEDIDOS(
PED_COD INT PRIMARY KEY,
PED_DATA DATE NOT NULL,
PED_HORA TIME NOT NULL,
PED_PREVISAO DATE NOT NULL,
PED_STATUS ENUM ('PENDENTE','CONCLUÍDO','EM ESPERA'),
PED_FORNECEDOR INT NOT NULL,
#CRIANDO A REFERENCIA PARA A CHAVE ESTRANGEIRA
#RESTRIÇÃO - NOME - CH. ESTRANGEIRA (CAMPO CRIADO) REFERENCIA A TABELA (CH. PRIMÁRIA)
CONSTRAINT FK_FORNECEDOR FOREIGN KEY (PED_FORNECEDOR) #DAR NOME A RESTRIÇÃO (CONSTRAINT)
REFERENCES FORNECEDORES(FORNEC_COD) #REFERENCIA A CHAVE PRIMÁRIA DE FORNECEDORES
);

#CRIANDO A TABELA RECEBIMENTOS VEIO DEPOIS PORQUE TEM DEPENDÊNCIA EM PEDIDOS
CREATE TABLE IF NOT EXISTS RECEBIMENTOS(
RECEB_DATA DATE NOT NULL,
RECEB_HORA TIME NOT NULL,
RECEB_QUANTPROD DECIMAL(10,3) NOT NULL,
RECEB_CONDICAO TEXT NOT NULL,
RECEB_PEDIDOS INT PRIMARY KEY,
CONSTRAINT FK_PEDIDOS FOREIGN KEY (RECEB_PEDIDOS) REFERENCES PEDIDOS(PED_COD));

#FASE 5: CRIANDO AS TABELAS ASSOCIATIVAS (ENTIDADES ASSOCIATIVAS)

#CRIANDO A TABELA PEDIDOS_PRODUTOS
CREATE TABLE IF NOT EXISTS PEDIDOS_PRODUTOS(
PDPR_PEDIDOS INT,
PDPR_PRODUTOS INT,
PRIMARY KEY(PEDIDOS_PRODUTOS),
PDPR_QUANT DECIMAL(10,3) NOT NULL,
CONSTRAINT PDPR_FK_PEDIDOS
FOREIGN KEY(PDPR_PEDIDOS)
REFERENCES PEDIDOS(PED_COD),
CONSTRAINT PDPR_FK_PRODUTOS
FOREIGN KEY(PDPR_PODUTOS)
REFERENCES PRODUTOS(PROD_COD)
);

#CRIAR A TABELA FILIAIS_PRODUTOS
CREATE TABLE IF NOT EXISTS FILIAIS_PRODUTOS(
FLPR_FILIAIS INT,
FLPR_PRODUTOS INT,
PRIMARY KEY(FILIAIS_PRODUTOS),
FLPR_QUANT DECIMAL (10,3) NOT NULL,
CONSTRAINT FLPR_FK_FILIAIS
FOREIGN KEY(FLPR_FILIAIS)
REFERENCES FILIAIS(FILIAIS_COD),
CONSTRAINT FLPR_FK_PRODUTOS
FOREIGN KEY(FLPR_PRODUTOS)
REFERENCES PRODUTOS(PROD_COD)
);

#CRIANDO A TABELA FORNECEDORES_PRODUTOS
CREATE TABLE IF NOT EXISTS FORNECEDORES_PRODUTOS(
FRPR_FORNECEDORES INT,
FRPR_PRODUTOS INT,
PRIMARY KEY(FORNECEDORES_PRODUTOS),
CONSTRAINT FRPR_FK_FORNECEDORES 
FOREIGN KEY(FRPR_FORNECEDORES)
REFERENCES FORNECEDORES(FORNEC_COD),
CONSTRAINT FRPR_FK_PRODUTOS
FOREIGN KEY(FRPR_PRODUTOS)
REFERENCES PRODUTOS(PROD_COD)
);
